spring:
  application:
    name: mall-admin
  thymeleaf:
    cache: false #开发时关闭缓存，不然无法看到实时页面
    mode: HTML #用非严格的html
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mall-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    cache-enabled: true
  type-aliases-package: com.tiny.mall.admin
  mapper-locations: classpath:mapper/*.xml

